" INSERT "source ~/file/location/vimrc" to ~/.vimrc

filetype plugin on
syntax on

" PLUGINS
source ~/workspace-sep/dotfiles/vim/autoload/plug.vim

call plug#begin('~/dotfiles/vim/bundles')

	Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
	" Plug 'valloric/youcompleteme'

call plug#end()


" APPEARANCE
    set number " SHOW LINE NUMBERS
    set wrap " TURN ON LIN WRAPPING
    set wrapmargin=4 " WRAP LINES WHEN COMING WITHIN n CHARACTERS FROM SIDE
    set linebreak " SET SOFT WRAPPING
    set showbreak=... " SHOW ELLIPSIS AT BREAKING
    set autoindent " AUTOMATICALLY SET INDENT OF NEW LINE
    set ttyfast " FASTER REDRAWING
    set diffopt+=vertical
    set laststatus=2 " SHOW THE STATUS LINE ALL THE TIME
    set so=7 " SET 7 LINES TO THE CURSORS - WHEN MOVING VERTICAL
    set wildmenu " ENHANCED COMMAND LINE COMPLETION
    set scrolloff=3 " LINES OF TEXT AROUND CURSOR
    set shell=$SHELL
    set cmdheight=1 " COMMAND BAR HEIGHT
    set title " SET TERMINAL TITLE
    set showmatch " SHOW MATCHING BRACES
    set mat=2 " HOW MANY TENTHS OF A SECOND TO BLINK
    set tabstop=4 " TABS 4 SPACES 				
    set tw=80

