# INSERT "source file/path/location/bashrc" to the end of existing ~/.bashrc file

# CUSTOM BASH PROMPT ezpromt.net

export PS1="\[\e[31m\]\\$\[\e[m\]\[\e[31m\]\u\[\e[m\]\[\e[32m\]@\[\e[m\]\[\e[32m\]\h\[\e[m\]\[\e[31m\]_\[\e[m\]\[\e[34m\]\W\[\e[m\]:"

alias cd475='cd ~/workspace/OSU/CS-475'
alias cd362='cd ~/workspace-sep/CS362-004-S2018/projects/noblesal/dominion'
