# INSERT "source file/path/location/bashrc" to the end of existing ~/.bashrc file

# CUSTOM BASH PROMPT ezpromt.net

# BASH PROMPT
# export PS1="\[\e[31m\]\\$\[\e[m\]\[\e[31m\]\u\[\e[m\]\[\e[32m\]@\[\e[m\]\[\e[32m\]$HOSTNAME\[\e[m\]\[\e[34m\]~\[\e[m\]\[\e[34m\]\W\[\e[m\]:"


# OSU SSH 
#alias sshosu='ssh <userName>@access.engr.oregonstate.edu'

alias cd362='cd ~/workspace/OSU/CS-362;pwd;ls'

# TMUX TEMPLATES
alias tmuxd='~/dotfiles/tmux/templates/default.tmuxTemp'
